# Generated by Django 2.0.7 on 2018-11-01 09:52

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LargeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='大項目')),
            ],
        ),
        migrations.CreateModel(
            name='MiddleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='中項目')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycalendar.LargeItem', verbose_name='大項目')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SmallItem', models.CharField(blank=True, max_length=50, verbose_name='小項目')),
                ('summary', models.CharField(blank=True, max_length=50, verbose_name='概要')),
                ('description', models.TextField(blank=True, verbose_name='詳細な説明')),
                ('memo', models.CharField(blank=True, max_length=50, verbose_name='備考')),
                ('start_time', models.TimeField(default=datetime.time(7, 0), verbose_name='開始時間')),
                ('end_time', models.TimeField(default=datetime.time(7, 0), verbose_name='終了時間')),
                ('date', models.DateField(verbose_name='日付')),
                ('kosu', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), '時間（分）には半角英数字のみ指定できます。', 'invalid')], verbose_name='時間（分）')),
                ('totalkosu', models.PositiveIntegerField(blank=True, default=0, verbose_name='総時間（分）')),
                ('register', models.CharField(max_length=50, verbose_name='登録者')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('LargeItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycalendar.LargeItem', verbose_name='大項目')),
                ('MiddleItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mycalendar.MiddleItem', verbose_name='中項目')),
            ],
        ),
    ]
